### ISSUE TITLE
My shield is gone.

### ISSUE THREAD

**Issue by FatCat874** [TeamMidnightDust/SwordBlocking#1]
My shield disappear when I hold the sword even if I not holding it. Your mod is good, Thanks.

![Annotation 2021-01-04 184012](https://user-images.githubusercontent.com/76956613/103546500-852bf200-4ebc-11eb-919b-ebbb9adecd06.jpg)

**Comment by dada513** [comment]
Would be so nice if this only worked on swords.

**Comment by Motschen** [comment]
Made configurable in 1.2.0
