### ISSUE TITLE
Third person animation is broken once again

### ISSUE THREAD

**Issue by drown3d** [TeamMidnightDust/SwordBlocking#13]
(v1.3.1 for mc 1.20.1)

Trying to block while the main hand contains a sword will cause the arm with the sword to go down instead of up. 
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/acb98d3e-908b-4501-8e39-a07cd940e618)

In addition to this, the player appears to be in the "main hand blocking animation" if they're using any edible or drinkable item, or a bow, trident, crossbow, goat horn, or brush.
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/d6958d69-6681-45e6-a915-c4d14fa7d070) 
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/30814fec-2dce-48e2-bd3a-8eb2aa5ac428) 
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/3a088f90-3688-4d0d-9d09-373b63feb72b)

**Comment by lowercasebtw** [comment]
Yea I noticed this
