### ISSUE TITLE
"alwaysHideShield" is not properly reflected in first person

### ISSUE THREAD

**Issue by drown3d** [TeamMidnightDust/SwordBlocking#14]
(v1.3.1 for mc 1.20.1)

If "alwaysHideShield" is false, the shield will be hidden when holding a sword (and not other items) in third person, but not first person, where it will still render. 
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/077d5cf5-9a73-4e19-a542-82ec2bb926c6) 
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/8050c963-894e-4a82-a5bd-c52fe8e449a0)
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/57433fd5-596c-46f7-85b2-f1b5a2ca10a9) 
![image](https://github.com/TeamMidnightDust/SwordBlocking/assets/85593395/2e91fea8-32ff-45d4-beb0-110abdb9bfc3)

**Comment by Motschen** [comment]
I cannot reproduce this one, please list the other mods you are using.

**Comment by lowercasebtw** [comment]
Couldn't reproduce either. Make sure you don't have any other mods that could conflict with this mod & that you are on the latest version of the mod!
