### ISSUE TITLE
when open options game crashes

### ISSUE THREAD

**Issue by bentlyreal** [TeamMidnightDust/SwordBlocking#18]
So when i press options like anywhere it crashes with the note as The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_344.<init>(int, int, int, int, int, int, int, net.minecraft.class_2960, int, int, net.minecraft.class_4185$class_4241, net.minecraft.class_2561)' i hope this gets fixed

**Comment by Motschen** [comment]
This was caused by the mod not being updated to 1.20.6 at the time of this report. It should now be fixed.
