### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by Shad0wGithub** [TeamMidnightDust/SwordBlocking#5]
i have no idea why but in third person the animation is completely stuffed up and in first person it works but the shield isnt hidden
![broken](https://user-images.githubusercontent.com/87593953/138623838-173d9cbb-2c45-4097-ba7e-f3a8dba26fdd.png)
![broken1](https://user-images.githubusercontent.com/87593953/138623842-5700ee75-04a5-4182-94c2-d6f8c03e910a.png)

(edit i found out why i have a low shield texture pack but it still doesnt work in third person)

**Comment by Motschen** [comment]
Fixed in 1.2.0
