### ISSUE TITLE
Sword model is actually flipped when parrying 

### ISSUE THREAD

**Issue by 0DamI0** [TeamMidnightDust/SwordBlocking#6]
The sword is simply flipped the other way.
The second image is with old-animations and the right way while the third with sword-blocking isn't.
![2022-02-25_18 55 51](https://user-images.githubusercontent.com/85436247/155764563-502af13b-a4e5-45b6-819d-a37b64db3e58.png)
![2022-02-25_18 55 50](https://user-images.githubusercontent.com/85436247/155764586-5cc984ec-5429-4a0a-9a36-a086fdf6f992.png)
![2022-02-25_18 59 40](https://user-images.githubusercontent.com/85436247/155764628-619455d6-5f23-4596-90c3-ed6e3182833b.png)
I'd like to get this fixed because old-animations and sword-blocking work tremendously well together and i use them every day.
The only thing is obviously this. I'm playing on 1.16.5 and i hope for a fix even tho the version is abandoned. Thanks for the attention.

**Comment by whatbuttt** [comment]
Where did you get the old animations mod from?

**Comment by Motschen** [comment]
Fixed in 2.0.0 :)
