### ISSUE TITLE
Crashes on start-up on 1.19.3

### ISSUE THREAD

**Issue by Poopooracoocoo** [TeamMidnightDust/SwordBlocking#9]
Sword Blocking version: 1.1.0 - 1.17+
Fabric API version: 0.73.0+1.19.3
Fabric Loader version: 0.14.13
Minecraft version: 1.19.3
Launcher: Prism Launcher 6.1

Logs: https://mclo.gs/VnVLy8P

**Comment by Motschen** [comment]
Fixed in 1.2.0 :)
